tifapp/FitnessProject

App.tsx, README.md, components/AcceptMessageButtons.tsx, components/ExpandingTextInputWithNameInput.tsx, components/InternetConnectionBanner.tsx, components/LikesList.tsx, components/LocationButton.tsx, components/PostImage.tsx, components/PostItem.tsx, components/ProfileImageAndName.tsx, components/StatusIndicator.tsx, components/basicInfoComponents/StatusPicker.tsx, components/postComponents/LikeButton.tsx, components/postComponents/PostHeader.tsx, global.d.ts, hooks/fetchName.ts, hooks/statusColors.ts, package-lock.json, package.json, screens/FeedScreen.tsx, screens/MessageScreen.tsx, screens/ProfileScreen.tsx
Fixed typescript issues in profileimageandname component and organized lines Fetchname hook now saves the fetched data to the cache Fixed styling in post header
Fixed mismatched variable names in post image/post item components, images can properly display now
=> Renamed imageURL variable to imagePartialURL in feed screen and reorganized lines

App.tsx, package-lock.json, package.json, screens/ActivitiesScreen.tsx
+ Added a navigation container to sandbox screen and moved sandbox screen to a new file
=> Fixed user sign in flow and missing sandbox imports

.eslintrc.json, .husky/pre-commit, .lintstagedrc.cjs, lib/GraphQLOperations.ts, lib/MultiplexedError.ts, lib/UserNotifications.ts, lib/linkingConfig.ts, lib/posts/PostIDComponents.ts, lib/posts/UserPost.ts, lib/posts/UserPosts.tsx, lib/posts/helpers.ts, lib/posts/index.ts, package-lock.json, package.json, screens/HomeScreen.tsx, tests/AmplifyGraphQLOperations.test.ts, tests/HomeScreen.test.tsx, tests/MultiplexedError.test.ts, tests/helpers/GraphQLOperations.ts, tests/helpers/Matchers.ts, tests/helpers/Promise.ts, tests/helpers/UserNotifications.ts, tests/helpers/unimplemented.ts, tests/linkingConfig.test.ts, tests/postUI.test.tsx, tests/posts/GraphQLUserPosts.test.ts, tests/posts/PostIDComponents.test.ts, tests/posts/UserPostReplyScreen.test.tsx, tests/posts/helpers.ts
This PR simply just adds a linting and testing step every time you run `git commit`. This ensures that we don't introduce tests that fail into any remote branches or PRs.
=> Linting and Testing Precommit Hooks

.github/workflows/auto-label.yml, .github/workflows/build.yml, .husky/pre-commit, components/eventForm/EventFormValues.ts, package-lock.json, package.json, tests/events/EventForm/EventFormScreen.test.tsx, tests/events/EventForm/LocationBanner.test.tsx, tests/events/EventForm/helpers.ts, tests/location/search/AsyncStorageSearchHistory.test.ts
* Add a github action to add a label with the number of reviews a PR has, and add a "merge conflict" label if it exists
* Add a github action to run tests and compile the project
* Removed pre-commit hook
* Fixed dependency capitalization that caused github action to fail
* Set timezone on tests to utc
* Clear query cache after react query tests to prevent github tests from stalling
=> Add github action to set up project files

package-lock.json, package.json
This PR simply installs the latest version of jotai.
=> Install Jotai

lib/location/Location.ts, lib/location/Placemark.ts
This PR simply adds a new location type that combines both the `LocationCoordinate2D` and `Placemark` types.
=> New Location Type

package-lock.json, package.json
This PR simply installs faker.js for mocking data in tests and UI previews, and react-native-fast-image for performant image loading and caching.
=> Install Faker.js and React Native Fast Image

README.md
For this pull request, I have been developing the frontend README by adding in new sections based on the discussions we had, while preserving a good portion of the contents of the original README. 
If there is any section you would like to be included, or any new information you would like to be highlighted in the frontend README, please make a comment on this PR. This is still a work-in-progress.
=> Markdown implementation + Major Frontend README changes

STYLEGUIDE.md
The long awaited... Keep in mind that this is a reference, and that we'll (hopefully) update these guidelines over time. Anyways, since this is a reference, don't worry about reading it end-to-end. Rather, if you're unsure about how to go about something, look it up in the reference.
Anways, most code examples have a good and bad version, and every guideline has some justification outside of simple style preferences like `snakeCase > camel_case`.
=> Add code style guide

.eslintrc.json, .storybook/.ondevice/Storybook.tsx, .storybook/.ondevice/storybook.requires.js, .storybook/components/SearchBar/SearchBar.stories.tsx, .storybook/components/TextField/TextField.stories.tsx, components/SearchBar.tsx, components/Text.tsx, components/TextFields.tsx
A generic text field components that match the designs. I also included a `PasswordTextField` component and updated the implementation of `SearchBar` to use the generic text field under the hood.
=> Generic text field

.storybook/.ondevice/Storybook.tsx, .storybook/.ondevice/storybook.requires.js, auth/forgot-password/ForgotPasswordNavigation.test.tsx, auth/session/AuthBanner.test.tsx, auth/session/AuthBanner.tsx, auth/session/UserSessionContext.tsx, auth/session/index.ts
* This is a pull request for a component that renders one component if the user is signed in, and another if the user is not signed in.
* Currently, the implementation of the UI isn't available, but this serves as a good basis for that UI to be implemented.
=> AuthBanner logic + tests

.github/workflows/auto-PR-to-main.yml, easbuild.mjs, screens/ProfileScreen/Navigation/ProfileScreensNavigation.tsx
Fixes the crash experienced on Friday in the legacy profile screen. Additionally, we'll ensure that the eas build hooks are only ever run on CI.
=> Eas build fix

auth/CognitoHelpers.ts, auth/forgot-password/Environment.test.tsx, auth/sign-in/Authenticator.test.ts, auth/sign-in/Navigation.test.tsx, auth/sign-up/Environment.test.ts, jest.config.js, package-lock.json, package.json
* Adds the aws-amplify/react-native package required in v6 of Amplify, in order to test and use it properly.
* Also includes an adjustment of the jest.config in order to utilise "aws-amplify/auth" and "aws-amplify/react-native".
=> Add aws-amplify/react-native package

auth/CognitoSecureStorage.test.ts, auth/CognitoSecureStorage.ts, lib/SecureStore.ts, test-helpers/InMemorySecureStore.ts
* Updates the Cognito Secure Storage class to work with a keyChunkMappings system.
=> AWS Upgrade: Cognito Secure Storage

.storybook/.ondevice/Storybook.tsx, .storybook/.ondevice/storybook.requires.js, .storybook/components/RegionMonitoring/RegionMonitoring.stories.tsx, package-lock.json, package.json
In light of the region monitoring feature, I decided to add a simple test harness as a storybook story so that we can all use it to see how good it is. The story allows you to select the coordinate and presents a slider (which react natives makes you install a library for 🙄) that allows you to adjust the radius. The story will ask you for foreground location permissions first, so make sure you accept them. When selecting the location, the map is presented in a fullscreen modal, and all you have to do is tap and hold on the area to select it as the location. I also included live updates on your current location as a label, and the arrival banner appears once you arrive at the location.\
=> Region Monitoring Test Harness

event-details/Details.test.tsx, event-details/MockData.ts, shared-models/Event.ts
Replace `hasEndedEarly` (`boolean`) with `endedAt` (`Date | null`).
=> Event Details: Update Response

.storybook/components/EventDetails/EventDetails.stories.tsx, event-details/Countdown.test.tsx, event-details/Countdown.tsx, event-details/SecondsToStart.test.tsx, event-details/SecondsToStart.ts, event-details/arrival-tracking/ArrivalBanner.test.tsx, event-details/arrival-tracking/ArrivalBanner.tsx
Extracts the countdown logic so it can be shared across the actual countdown timer and the arrival banner. To do this, I created a hook called `useEventSecondsToStart` which does the countdown taking into account the `clientReceivedTime`. Then, I simply replaced the formatting logic in `Countdown.tsx` with a pure function rather than using the hook. Additionally, I also added a function to compute the `EventArrivalBannerCountdown` object needed for the arrival banner. To get a live countdown on the banner, you simply need to pass the `secondsToStart` returned by `useEventSecondsToStart` to `eventArrivalBannerCountdown` inside a component.
=> Event Details: Shared Countdown

api-client/TiFAPI.ts
Adds the block and unblock endpoints to `TiFAPI`.
=> API: Block and Unblock

api-client/TiFAPI.ts
Adds the get events by region endpoint.
For now, the endpoint is a POST with a body, but it should be updated to become a GET with query parameters.
=> Get events by region endpoint

lib/utils/CallbackCollection.ts, settings-storage/InternalMetrics.ts
Makes a small optimization to `CallbackCollection` to return a bound function from `.add`, as an arrow function uses more memory.
=> CallbackCollection Improvement

.github/workflows/link-ticket-on-pull-request.yml
=> trigger ticket link github action when pr is edited

.eslintrc.json
Turned off some ESLint rules that conflicted with prettier.
TASK_UVOItWdN
=> Remove a few ESLint Styling Rules

.storybook/components/SettingsScreen/SettingsScreen.stories.tsx, lib/SQLite.ts, settings-storage/LocalSettings.ts, settings-storage/PersistentStore.test.ts, settings-storage/PersistentStores.ts, settings-storage/UserSettings.ts
- Adds `UserInterfaceStyle` and `PreferredFontFamily` settings to local settings.
- Adds a new `PersistentSettingsStores` namespace containing functions to create `PersistentSettingsStorage` instances for local and user settings.
https://trello.com/c/7gsD1KkU
=> Settings: Update Storage

.storybook/components/SettingsScreen/SettingsScreen.stories.tsx, settings-boundary/AccountInfo.tsx, settings-boundary/BlockList.tsx, settings-boundary/NotificationSettings.tsx
Updates the settings screens to use the latest and greatest approved language.
https://trello.com/c/zPLvQuSl
https://trello.com/c/p3euWOcV
https://trello.com/c/zPLvQuSl
=> Settings: Update Language

babel.config.js, edit-event/DurationPicker.tsx, tsconfig.json
Creates a new module for the edit event flow.
https://trello.com/c/KH4nzJzH
=> Edit Event: New Module

.github/workflows/roswaal-bot.yml
https://trello.com/c/QmQsjQ2m/790-make-github-action-to-perform-roswaal-merge-close-operations
=> only send curl commands if branch starts with roswaal

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/tifapp/FitnessApp/MainActivity.kt, android/app/src/main/java/com/tifapp/FitnessApp/MainApplication.kt, app.config.js, ios/FitnessApp.xcodeproj/project.pbxproj, ios/FitnessApp/Info.plist
replace tifapp with tif in bundle identifiers since tifapp is taken on ios
=> Bundle Identifier adjustment

.storybook/components/RegionMonitoring/RegionMonitoring.stories.tsx, android/app/src/main/AndroidManifest.xml, arrival-tracking/Storage.test.ts, arrival-tracking/Storage.ts, arrival-tracking/Tracker.test.ts, arrival-tracking/Tracker.ts, arrival-tracking/geofencing/ExpoGeofencer.ts, arrival-tracking/region-monitoring/EventArrivalsTrackerRegionMonitor.test.ts
Adds background support to the region monitoring harness. This will be in draft as we debug the accuracy of the tracking.
https://trello.com/c/28WJIizX
=> Region Monitoring Harness: Improvements

.storybook/components/EditEvent/PragmaQuote.stories.tsx, edit-event-boundary/EditEvent.tsx, edit-event-boundary/Location.tsx
Adds the host map marker to the map on the edit event screen like how we do with the travel estimates in the details.
https://trello.com/c/nlDw85rB
=> Edit Event: Host Map Marker

components/form-components/Section.tsx, date-time/DateRangeFormatting.ts, edit-event-boundary/EditEvent.tsx
Adds 2 styling improvements to the edit event form:
1. Makes the section titles smaller (Subtitle -> Headline).
2. Adds an end time section that makes it easy to see when the event is ending.
https://trello.com/c/nlDw85rB
=> Edit Event: Form Styling

.storybook/.ondevice/Storybook.tsx, .storybook/.ondevice/storybook.requires.ts, .storybook/components/Haptics/Haptics.stories.tsx
A simple storybook story for haptics that we can use while we implement the native code interpreters for AHAP.
https://trello.com/c/GqWmCpYv
=> Haptics: Storybook

package-lock.json, package.json
Moves eas-cli to dev dependencies
Fixes this apple auth error
TASK_UNTRACKED
=> eas update

.storybook/.ondevice/Storybook.tsx, .storybook/.ondevice/storybook.requires.ts, .storybook/components/ProfileScreen/Avatar.stories.tsx, .storybook/components/RudeusEditor/RudeusAPI.ts, components/Avatar.test.tsx, components/Avatar.tsx, modules/tif-haptics/src/TifHapticsModule.tsx, package-lock.json, package.json
Implements default avatar (initials with color), intended for people without a profile image included
https://trello.com/c/iNjzhVU6/855-default-profile-avatar
=> Avatar Functionality

.storybook/.ondevice/Storybook.tsx, components/NameEntry/NameEntry.stories.tsx, core-root/NameEntry.tsx
https://trello.com/c/bteFtcXF/857-alpha-name-entry
=> Name entry story

.storybook/.ondevice/storybook.requires.ts, .storybook/components/EventDetails/EventDetails.stories.tsx, components/Avatar.tsx, components/CalendarDay.tsx, components/profileImageComponents/ProfileCircle.tsx, components/profileImageComponents/ProfileImageAndName.tsx, event/EventCard.test.tsx, event/EventCard.tsx, event/JoinEvent.tsx, event/LeaveEvent.tsx, event/Menu.tsx, event/UserAttendance.tsx
Improves the event-card design hierarchy to include a join button, event attendees, and much more. Here's a before and after:
There's still work that needs to be done on the general design aesthetics to ensure that they match what we have in mind for the journey instead, but at least this improves the hierarchy for now. Additionally, we should look into making a shared context for passing down the maximum font size multiplier in a follow-up as I think the drilling is starting to become a little much.
https://trello.com/c/QWlwe5VF
=> Event Card Update

api/TiFAPI.ts, arrival-tracking/region-monitoring/RegionMonitoring.ts, components/form-components/NamedIconRow.tsx, core-root/navigation/EventDetails.tsx, event-details-boundary/AttendeesList.tsx, event-details-boundary/Content.test.tsx, event-details-boundary/Content.tsx, event-details-boundary/Countdown.tsx, event-details-boundary/Details.tsx, event-details-boundary/TravelEstimates.test.tsx, event-details-boundary/TravelEstimates.tsx
Implements a Rudimentary Event Details View that includes some basic scaffolding around the details of the event whilst we work on the larger app aesthetics. We'll come back and tune this view design-wise once we know more about the journey and journaling aesthetics.
https://trello.com/c/fsmKgJXt
=> Event Details: Rudimentary View
