__mocks__/@react-native-async-storage/async-storage.js
jest.config.js
jest/setupNav.js
package-lock.json
package.json
tests/example.test.ts
tests/expoExample.test.tsx
tests/reactExample.test.tsx

#34 will be closed because the setup crashes when it encounters an import from expo. Expo is weird and I had to add a lot of obscure files (per documentation of some of the libraries we're using), so I can't guarantee that this is a full setup. Just be prepared to have to add more "setup" files in the jest folder and/or mocks in the "__mocks__" folder as needed, as NPM dependencies are unpredictable, and may cause the holy divine incantation to fail...

Jest with Expo Setup

---

.eslintrc.json
App.tsx
package-lock.json
package.json
screens/UserPostReplyScreen.tsx

This PR simply ensures that all types or interfaces are in PascalCase. Or basically:
```ts
interface mapMarker = {} // 🔴 Not PascalCase
interface MapMarker = {} // 🟢 PascalCase
```
Additionally, I also added the infamous react hooks exhaustive dependencies rule, which means this code now gets a linter warning:
```ts
const [state, setState] = useState("hello")
// 🟡 This will give a linter warning becuase state is not declared in the dependency array
useEffect(() => {
if (state === "hello") setState("world")
}, [])
```
The above rule is in some ways considered controversial, but I (and seemingly pretty much all react influencers worth their salt) think it's a good rule to ensure we are using `useEffect` for it's intended purpose (which is synchronization with  outside world dependencies). …

Eslint Rules for Type naming conventions and React Hooks

---

App.tsx
components/AppQueryClientProvider.tsx
tests/helpers/ReactQuery.tsx

Since the event form stuff finally brings on react query, I figured that I would just break out those tools into a separate PR since it's pretty disconnected to the event form entirely.
It basically includes a `TestQueryClientProvider` and an `AppQueryClientProvider`, the former is for tests which you could probably guess and the latter is for wrapping the actual app.
The test provider basically disables retries and sets all retry delay to 0 so that when we need to test error cases for fetching it doesn't ping the fetch function a crap ton of times.
The app provider just creates a default `QueryClient`, but I expect that we would configure it differently once we need to in the future.

React Query config

---

.storybook/components/HexColorPicker/HexColorPicker.stories.tsx
components/EventItem.tsx
components/eventForm/ColorPicker.tsx
components/eventForm/EventFormValues.ts
lib/events/Event.ts
lib/events/EventColors.ts
lib/events/Events.ts

This PR simply converts the `EventColors` namespace into an enum such that you can now use `Object.values`, `Object.keys`, `Object.entries`, etc. to do transforms on the colors like @seanim0920 suggested. I also updated the `Event` type to use this new enum rather than a string.

Update Event Type

---

lib/date/DateRange.ts
tests/date/FixedDateRangeFormatting.test.ts

Currently when 2 dates are the same (eg. `startDate = today = today at 5pm, endDate = today at 5pm`) calling `formatted` on `FixedDateRange` will return this for the above example: `Today 5pm - 5pm`.
This obviously is very redundant, so this PR simply makes that become `Today 5pm`.

Fix: Date Range formatting when dates are in the same minute

---

lib/Array.ts
lib/AsyncStorage.ts
lib/location/search/Client.ts
lib/location/search/History.ts
lib/location/search/SearchResult.ts
lib/location/search/index.ts
package-lock.json
package.json
tests/ArrayUtils.test.ts
tests/AsyncStorageUtils.test.ts
tests/location/search/SearchHistory.test.ts

The location search feature allows for the user to search existing addresses using any arbitrary text. However, the user may have no idea of _what_ to search, or maybe they just want to host an event in the same location they attended last week. And so my proposed solution to that is to store their most recent results on the search screen so they can quickly access them. 
#63 introduced what an individual search result looks like in UI, and one of the things you may have noticed is that there's a different icon on the last result in the UI screenshot which represents a result that comes from the user's search history. Naturally, we need some way to tell if a result is part of the user's search history, and that's what this PR is for... A way to persist location search history using …

Location Search History Persistence

---

components/eventForm/LocationBanner.tsx
lib/NullsToUndefined.ts
lib/location/Geocoding.ts
lib/location/Placemark.ts
tests/NullsToUndefined.test.ts
tests/location/PlacemarkFormatting.test.ts
tests/location/helpers.ts

Since js has both `null` and `undefined`, and react tends to prefer `undefined` for optional prop values, I decided to covert the `Placemark` type to hold a bunch of possible undefined values instead of a bunch of `string | null` types. This removed the ridiculous `placemark.someField ?? undefined` dance that was performed several times.
Additionally, I also added a generic utility to convert null values on any object to undefined, which should make life easier when working with react props. It's called `nullsToUndefined`, and it will mostly be useful in turning 3rd party library types that use null into ones that use undefined.

Cleanup: Represent Null values on Placemark as undefined

---

.storybook/.ondevice/Storybook.tsx
.storybook/.ondevice/storybook.requires.js
.storybook/babel.config.js
.storybook/components/EventForm/EventForm.stories.tsx
babel.config.js

Imports in storybook should work as expected now by using the same babel config as the root project.
Remaining issues:
* VS still doesn't recognize the @path shortcuts in storybook, but they should build properly in expo
* Storybook adds a margin on top of the stacknavigator for some reason. Adding "headerStatusBarHeight" to 0 fixes it but it would need to go in the stack navigator directly, which I didn't include here.

Fix babel storybook issue

---

components/Map.tsx
jest.config.js
jest/setupMapMock.jsx
screens/ActivitiesScreen.tsx
tests/components/Map.test.tsx

This PR cleans up the map component interface, whilst also just renaming it to `Map`. It naturally also includes a jest mock so that the map component is usable for testing. I've also removed some unused functions atm since we probably won't need them for the near future.

Cleanup: Get Map component under a test harness

---

lib/dependencies/DependencyHooks.tsx
lib/dependencies/DependencyKey.ts
lib/dependencies/DependencyValues.ts
tests/dependencies/DependencyHooks.test.tsx
tests/dependencies/DependencyValues.test.ts
tests/dependencies/helpers.ts

This PR requires that `SetDependencyValue` or `UpdateDependencyValue` is used for all dependency keys in a given test context. If a dependency key attempts to use its default value inside a test, the `DependencyValues` class will throw an error (which is highly likely to cause a test failure).
There are 2 reasons for why this is a good idea:
1. It prevents tests from accidentally making AWS calls, tracking analytics, or doing other costly operations.
2. It ensures that when you write tests, you don't miss covering important side effects. By explicitly requiring that you give a preset value for a dependency key, you will naturally think about how the component under test uses the dependency.

Update: Make a test fail when it uses the default value from a dependency key

---

components/Text.tsx

#92 Added the open sans font and a hook to load the font. This PR now adds some preset text components since more design details have been fleshed out. Each text component takes in the standard `TextProps` so they can be used like the normal react native text component. Here's an image for reference:

OpenSans Text Components

---

hooks/UserLocation.ts
lib/location/UserLocation.ts
tests/location/UserLocation.test.ts

This PR adds a wrapper around getting the user's current coordinates similar to the way we did it with tracking.

Current User Coordinates Expo Query

---

components/common/Buttons.tsx
lib/ButtonStyle.ts

This PR includes the button components shown in the designs and includes a dark variant and light variant. The title and onPress function are passed in through props so the components are reusable.

Button Components Shown in Design

---

hooks/UserLocation.ts

This PR simply adds a usage example for `useTrackUserLocation`.

Add code example docs for useTrackUserLocation

---

components/TextFields.tsx

It seems like I forgor this the first time, but the lock icon now has an accessibility label.

Add accessibility label to Password text field

---

.storybook/components/TextField/TextField.stories.tsx
components/TextFields.tsx

This PR removes the `isShowingPasswordContents` and `onShowPasswordContentsChanged ` from `PasswordTextField` and makes them internal to the component. This ensures that we don't need a `useState` just for that lock icon.

Make password visibility internal

---

App.tsx
auth/ChangePassword.test.tsx
auth/ChangePasswordForm.tsx
components/TiFQueryClientProvider.tsx
hooks/Geocoding.tsx
hooks/UserLocation.tsx
hooks/useApiQuery.ts
lib/ReactQuery.ts
package-lock.json
package.json
screens/EventAttendeesList/AttendeesListScreen.tsx
screens/EventFormScreen.tsx
screens/ExploreEvents/models.ts
screens/ExploreEvents/useExploreEvents.ts
screens/LocationSearch/Picker.tsx
tests/Haptics.test.tsx
tests/Reporting.test.tsx
tests/events/EventForm/EventFormScreen.test.tsx
tests/events/EventForm/LocationBanner.test.tsx
tests/events/ExploreEvents.test.tsx
tests/helpers/Alerts.ts
tests/helpers/ReactQuery.tsx
tests/helpers/Timers.ts
tests/location/LocationSearch.test.tsx

Recently it was discovered that our version of react native testing library was a little outdated, but the main problem that triggered this PR was that `waitFor` was acting weird. In particular, it required code to be written like this:
```ts
// 🔴 ???
await waitFor(() => {})
// ✅ This passes because of the prior waitFor
expect(result.current.status).toEqual("success")
expect(result.current.status).toEqual({...})
```
And code like this:
```ts
await waitFor(() => expect(result.status).toEqual("success"))
```
Would fail when it really shouldn't.
Well the good news is that this happened to be a bug with the old version of rntl, so it was updated here. However, this broke a few tests, particularly in the explore and change password features, since they were making assertions based on the old …

Fix test infrastructure + React Query

---

components/TextFields.tsx

Something was weird when I was trying to test entering passwords, turns out it was the beloved autocorrect. Yeah, lets not give the users that pleasure either.

Remove Autocorrect from Password Text Fields

---

.storybook/.ondevice/Storybook.tsx
.storybook/.ondevice/storybook.requires.js
.storybook/components/SignUp/SignUp.stories.tsx
.storybook/components/VerificationCode/VerifyCode.stories.tsx
auth/AuthSection.tsx
auth/AuthTextFields.tsx
auth/Email.test.ts
auth/Email.ts
auth/PhoneNumber.test.ts
auth/PhoneNumber.ts
auth/VerifyCode.test.tsx
auth/VerifyCode.tsx
auth/index.ts
auth/sign-up/index.ts
components/common/Toasts.tsx
components/profileImageComponents/ProfileImageAndNameWithFriend.tsx
lib/String.ts
package-lock.json
package.json
screens/ProfileScreen/ProfileView.tsx

All of the auth flows will at least have 1 edge case which require a verification code, so this PR creates a generic component and hook for verification flows called `AuthVerificationCodeForm` and `useAuthVerificationCodeForm` respectively.
Additionally, there's also a `USPhoneNumber` and `EmailAddress` types which are not only useful for validation purposes, but they also include a `formattedForPrivacy` computed property which hides sensitive details about their real value. This allows for the common pattern in which apps will "star out" a phone number minus the last 4 digits.
I also modified the existing Toast View that we had since it was ancient, and needed to communicate that the verification code was resent (or failed to be resent) when "Resend it." was tapped. This toast view was …

Generic Verification Code Form

---

.storybook/components/TextField/TextField.stories.tsx
components/TextFields.tsx

Normally text field focus is done through refs, and apparently the `TextFieldProps` did not accept a ref. No matter, it turns out that even if `TextFieldProps` accepted a ref, it would've required that all other Text field components wrapping ours (Auth text fields for instance) use `forwardRef`. And don't even get me started on what it takes to get typesafety for that.
So instead we'll use a simple `isFocused` prop, and handle the ref BS inside our text field. Additionally, this allows us to completely get rid of `forwardRef`. Furthermore, this also makes focus state a lot more easily testable.
I also cleaned up the existing text field code, mainly the duplication.
PS. There is 1 gotcha around autofocusing a text field when the view loads, for that use `autoFocus` instead of `isFocused` …

Add stateful focus to custom Textfields

---

.storybook/.ondevice/Storybook.tsx
.storybook/.ondevice/storybook.requires.js
.storybook/components/ChangePassword/ChangePassword.stories.tsx
auth/AuthTextFields.tsx
auth/ChangePassword.test.tsx
auth/ChangePasswordForm.tsx
components/TextFields.tsx
screens/ProfileScreen/Navigation/ProfileScreensNavigation.tsx

This PR updates the change password to match the rest of the auth screens. Additionally, there were some bugs in the change password that needed to be fixed which required that we also need to display multiple error messages to the user.
Furthermore, the `isFocused` field was causing some weird issues on iOS when trying to do the "focus the next field when the user taps next on their keyboard" so we're back to using refs. This of course involved wrapping every single text field component with `forwardRef`...
Additionally, the text field error now animates in when it appears, which makes layout animations possible within these forms (as seen in the new change password screen).
I also added a storybook story for the screen and removed the password re-enter since it was an extra step that …

Update change password

---

.storybook/components/SignUp/SignUp.stories.tsx
auth/AuthTextFields.tsx

This PR updates the toggle used in the `AuthShadedEmailPhoneTextField` component to use a refresh icon instead of having buttons that indicate which mode the user is in. The reasoning for this is to illustrate that pressing the button will actually switch the text field to use email or phone number.

Update email-phone toggle

---

auth/sign-up/Navigation.test.tsx

It seems a recent change caused sign-up tests to get the act error. It turns out that it has to do with some random component animation in react-navigation, so I simply faked the timers and ran `jest.runAllTimers` in an act block at the end of each test.

Fix Sign-Up tests act warning

---

.storybook/components/ForgotPassword/ForgotPasswordForm.stories.tsx
auth/AuthTextFields.tsx
auth/CognitoHelpers.ts
auth/Models.test.ts
auth/Models.ts
auth/forgot-password/Environment.test.tsx
auth/forgot-password/Environment.ts
auth/forgot-password/ForgotPasswordNavigation.test.tsx
auth/forgot-password/ForgotPasswordNavigation.tsx
auth/sign-in/Authenticator.test.ts
auth/sign-in/Authenticator.ts
auth/sign-up/Environment.ts

This PR added the ability to resend the forgot password code. I also made `USPhoneNumber` return the e.164 formatted string inside its `toString` instead of as a separate property. This removed the cognito format function in exchange for a less verbose `toString`.

Resend forgot password code + cleanup cognito code

---

components/ContentText.test.tsx
components/ContentText.tsx
event-details/Event.test.ts
event-details/Event.ts
lib/users/UserHandle.ts

Updates the `EventHandle` class to support the new format we agreed on. Additionally, the initializer is now public provided that you have and event id and event name.
I also updated the linkify parsing using a similar hack to the zod optional parsing approach so that we don't need to parse handles multiple times (once in linkify parsing, the other in `ContentText`).

Event Handle New Format + Cleanup Linkify Parsing

---

.storybook/components/ContentText/ContextText.stories.tsx
components/ContentText.tsx
lib/Reanimated.ts

Adds a new expanding text component that uses `ContentText` under the hood so that handles and whatnot are rendered. It also has a much smoother fade animation when the text expands, and doesn't rely on a hardcoded text height such that it works with dynamic type.
Of course, solving the layout issues was quite a bit hacky, and the approach used splits the text up into 2 groups based on what is supposed to render and what isn't.

Read more text

---

.storybook/components/ContentText/ContextText.stories.tsx
content-parsing/ContentText.test.tsx
content-parsing/ContentText.tsx
content-parsing/EventHandle.test.ts
content-parsing/EventHandle.ts
lib/AppColorStyle.ts
lib/Color.test.ts
lib/Color.ts

This PR experiments with adding a color to the event handle so that the event name when rendered in text could be the same color of the actual event. This changes the handle format slightly of course:
`!<name-length>|<id>/<name>` -> `!<name-length>|<id>/<hex-color>/<name>`
To do this, I added a new `ColorString` class which can be constructed by parsing a typical hex color string. However, this class also can serve as a utility for manipulating attributes of colors such as opacity, which we do a few times especially around background and border colors.
Anyways, here's an event name colored in green for reference:

Add color to Event Handles

---

.storybook/components/Explore/Explore.stories.tsx
.storybook/components/LocationSearch/LocationSearch.stories.tsx
App.tsx
app.config.ts
hooks/UserLocation.tsx

This PR adds a hook similar to `useRequestForegroundLocation` permissions called `useRequestBackgroundLocationPermissions`.
It also adds a reason description on iOS that shows up when the user receives the permissions prompt for both foreground and background location permissions.

Background Location Permissions Setup

---

event-details/arrival-tracking/Geofencing.ts
event-details/arrival-tracking/Tracker.test.ts
event-details/arrival-tracking/Tracker.ts
event-details/arrival-tracking/models.ts
lib/location/Location.ts

This PR makes the tracker class observe geofencing updates, and post an arrival or departure respectively. It does so by grabbing all upcoming event arrivals near a particular coordinate, then doing the respective `"arrived"` or `"departed"` operation on all the arrivals. In some cases, we may not have had a refresh yet, and the `EventArrivalOperationResult` type contains cases for what happens when we try to arrive/depart from an outdated arrival. The tracker uses these results and updates the upcoming arrivals and geofenced coordinates accordingly.
I also had to make some modifications to the `checkIfCoordsAreEqual` method to compare against an epsilon, as coordinates may lose precision when they are persisted.
There's also some trickery to ensure that we're only subscribed to …

Arrivals: Handle Geofencing Update

---

auth/sign-in/Authenticator.test.ts
auth/sign-in/Authenticator.ts
auth/sign-in/Navigation.test.tsx
auth/sign-up/Environment.test.ts

Reimplements the `CognitoSignInAuthenticator` using the new v6 functions. Also makes the SignInNavigation tests mock the authenticator directly so we don't need to change the tests due to future package changes.

Auth Upgrade: Sign In

---

.storybook/components/AttendeesList/AttendeesList.stories.tsx
App.tsx
event-details/EventDetailsLoading.test.tsx
event-details/EventDetailsLoading.tsx
lib/InternetConnection.tsx
lib/utils/UseEffectEvent.ts
test-helpers/ExpectNeverOccurs.ts
test-helpers/InternetConnectionStatus.ts

The internet is flaky, and it would be very convenient for the user to know about that. This PR makes it so that the event details (and in the near future other major screens like explore) are automatically refetched when the internet comes back online after it has been down for some time.
First and foremost, I made an `InternetConnection` file in the `lib` folder and created an interface (`InternetConnectionStatus`) that can be injected through a context provider (`InternetConnectionStatusProvider`) for testing and storybook purposes. It turns out that it would be pretty hard to preview any future connection status UI without that context provider as turning off your wifi means losing connection to the expo dev server. This context is used by a `useIsConnectedToInternet` hook which uses …

Event Details: Automatically refetch when the internet comes back up

---

api-client/TiFAPI.ts
event-details/EventDetailsLoading.test.tsx
event-details/EventDetailsLoading.tsx
event-details/MockData.ts
shared-models/Event.ts

- Uses `nullable` instead of `optional` on the zod schemas which requires null to be explicitly passed.
- Adds a `hasEndedEarly` property directly on `CurrentUserEventResponse` which can be used to detect when the host has cancelled the event while it was ongoing.
- Moves `timezoneIdentifer` to the `location` object as per requested by the backend.

Event Details: Update Event Type

---

api-client/client.test.ts
api-client/client.ts

This PR adds the ability to pass in `undefined` in the `query` property when using `TiFAPIFetch` since some endpoints needed it.

API Client: Add Optional Query Parameter Support

---

api-client/TiFAPI.ts
shared-models/ChatToken.test.ts
shared-models/ChatToken.ts

Adds zod schemas and method on `TiFAPI` for the join endpoint. The schema for the chat token request was a little non-trivial, so I added some simple tests for it even if they don't handle every possible case. Additionally, I also added a `literalErrorSchema` function which creates zod schemas that match the errors returned from the api.

Event Details: Join Endpoint

---

.eslintrc.json
event-details/arrival-tracking/ArrivalBanner.tsx

We hated this rule in unison, so it shall be banished.

Eslint: Remove react in scope

---

.storybook/components/ContentText/ContextText.stories.tsx
content-parsing/ExpandableContentText.tsx

The previous component had 2 flaws:
1. It didn't update when the text changed.
2. It didn't render event handles properly.
This PR fixes both of those problems. First of all, the reason event handles weren't rendered properly was because we were combining the raw text from the text lines rendered by `ContentText`, which would strip any metadata characters needed to render event handles. This was convenient before, since we could easily separate the collapsed text from the expanded text, and then gracefully animate in just the text that needed to be expanded. 
However, in order to fix this we cannot rely on the raw text lines anymore, and instead must rely on rendering everything within `ContentText` itself. Thankfully, we can recreate the animation bits by applying a sneaky cross-fade …

Fix Expandable Content Text

---

event-details/arrival-tracking/Tracker.test.ts
event-details/arrival-tracking/Tracker.ts
event-details/arrival-tracking/UpcomingArrivals.test.ts
event-details/arrival-tracking/UpcomingArrivals.ts

In light of region monitoring for the UI, when the user disabled background location permissions we won't be able to geofence any locations in the background. Therefore, we aren't really tracking them, and we shouldn't even consider them as being a part of the tracker.
So I added 2 things to make this happen:
1. A `requireBackgroundLocationPermissions` function that takes in a `UpcomingEventArrivals` instance, and returns a new `UpcomingEventArrivals` instance that blocks reads and writes if the user has the permissions disabled.
2. I made sure that the tracker publishes an empty update to the `subscribe` method when the given `EventArrivalsGeofencer` throws after calling `replaceAllGeofencedRegions`.
The first needs to be done because the user may retroactively disable background …

Event Arrivals: Prevent arrivals from being tracked when background location permissions are disabled

---

.storybook/components/ContentText/ContextText.stories.tsx
.storybook/components/EventDetails/EventDetails.stories.tsx
content-parsing/ExpandableContentText.tsx
event-details/JoinEvent.test.tsx
event-details/JoinEvent.tsx
event-details/arrival-tracking/region-monitoring/MockRegionMonitors.ts
event-details/index.ts

The initial join flow UI that follows up on #242. Though, this code does make a few naming changes with regards to the hook, but the functionality remains exactly the same.
I'm going to keep this PR in draft for 2 reasons:
1. I need to hear back on what exact messages to use for the permission modals.
2. The code to control the presentation of the bottom sheet modal is really hacky.
With regards to point 2, the main reason for the hacks was to ensure that the modals present sequentially 1 after the other in a graceful way. I originally implemented it using 2 separate `BottomSheetModal` components, but this created a quite nasty and abrupt animation when switching between the 2 sheets after enabling notification permissions. Essentially, the trick is to wait for the first one to dismiss …

Event Details: Join Flow UI

---

api-client/TiFAPI.ts

* Adds a leaveEvent function to the TiFAPI class, to allow for the leaveEvent flow to utilise TiFAPI.
Response codes: 
- 204: Success case, no-content
- 400: Host trying to leave, user already left event (counts as success case to hook)
- 403: Event already been cancelled, or otherwise ended

Add leaveEvent function to tifAPI

---

lib/SQLite.ts
lib/utils/Array.ts
lib/utils/DeepNullable.ts
location/MockData.ts
location/search/MockData.ts
location/search/Models.ts
location/search/RecentsStorage.test.ts
location/search/RecentsStorage.ts
location/search/SearchClient.test.ts
location/search/SearchClient.ts
location/search/SearchResultsList.tsx
shared-models/Location.ts
test-helpers/SQLite.ts

Migrates the functions to load the user's recent locations from AsyncStorage to SQLite. Since now the functions depend on the `TiFSQLite` class, I decided to make an interface called `RecentLocationsStorage` with an accompanying `SQLiteRecentLocationsStorage` implementation class. Due to the creation of this new interface, I had to modify the functions in `SearchClient.ts` to accept an instance of the interface as a parameter. Additionally, I took this as an opportunity to clean up the tests a little where I fixed a bug that was previously there in the process. The bug simply only counted a location as a recent location if it had an annotation, even though no annotation is required for it to be considered a recent location.
For the recent locations themselves, I simply created a table …

SQLite Migration: Recents Storage

---

.eslintrc.json

Allow dashed object keys to use for union types

Allow dashed object keys

---

.storybook/components/EventDetails/EventDetails.stories.tsx
event-details/Menu.test.ts
event-details/Menu.tsx

Replaces the "Edit Event" menu action with a new action to block/unblock the host since we display the edit event action next to the host row on the details screen.
I made some changes to the `EVENT_MENU_ACTIONS` config object which allow the title and image to be computed from a function so that creating dynamic content was easier.

Event Details: Replace Edit Menu Action with Block Toggling

---

event-details/Details.tsx
event-details/Query.ts
screens/ExploreEvents/useExploreEvents.ts
shared-models/Event.ts
shared-models/User.ts
shared-models/query-keys/Event.ts
tests/events/ExploreEvents.test.tsx

Some of the query keys will need to be shared, so I made a `query-keys` folder inside `shared-models`. This doesn't cover `useQuery` instances that are shared atm, as we don't have any instances of that as of now.

Shared Query Keys Folder

---

event-details/JoinEvent.test.tsx
event-details/JoinEvent.tsx
event-details/Menu.test.tsx
event-details/TestHelpers.tsx

Ensures to update the user attendee status to `"attending"` when joining an event using the same methods as #280. I also removed the `onSuccess` handler since its original intention was to do the query client update.

Event Details: Update Query Client on successful join

---

lib/SQLite.ts
lib/Sqlite.test.ts
test-helpers/SQLite.ts

Opening a SQLite database can fail for a variety of reasons. Some include:
- Permissions issues
- Lack of disk space
- Path not found
- etc.
In our case, we use SQLite mainly for storing client-side data. Since that data is not necessarily integral to the app it wouldn't make sense to alert the user about any of the above opening failure cases. Therefore, the best approach is to fail silently. For this, I've made it so that if the call to `openDatabaseAsync` fails for any reason, I fallback to calling `openDatabaseAsync` with an _in memory_ path. This way, sqlite operations can proceed somewhat normally without being a deterrence to the user experience.
`TiFSQLite` now accepts a new argument in its constructor which performs the opening logic to which the constructor calls with the …

Sqlite: Fallback to in-memory database when opening fails

---

lib/SQLite.ts

Adds a `warn` level log message when SQLite fails to open for any reason. I made sure to put the error message, expo error code, and path in the metadata.

SQLite: Add Warn Log Message on Open Failure

---

.storybook/components/SettingsScreen/SettingsScreen.stories.tsx
lib/Fonts.ts
settings-boundary/AppearanceSettings.tsx
settings-boundary/components/ScrollView.tsx
settings-boundary/components/Section.tsx
settings-boundary/index.ts

Implements the settings screen that allows the user to change the theme to light or dark mode and the font to Open Dyslexic. This PR does not implement dark mode or font changes in the UI, but just the screen that allows the user to do so.
On iOS the open dyslexic font seems to have an inherent top margin of 4. To level that text with Open Sans in the font picker, I needed to add a negative top margin to counteract this.
https://trello.com/c/7gsD1KkU

Settings: Appearance Settings

---

lib/AppState.tsx
lib/utils/UseDismisaal.test.tsx
lib/utils/UseDismissal.ts

Creates a hook that runs a function when either the current component unmounts, or when the app is backgrounded.
Some screens, like the block list, debounce any changes the user may make to them (eg. debouncing when unblocking users so that the backend can unblock many users at once rather than make a separate API call for unblocking each user). Debouncing relies on `setTimeout` which is paused when the app backgrounds. So when the app backgrounds, or when the user leaves that screen, we should skip the debounce wait and flush any pending changes.
This new hook, `useDismissal` allows for that. You pass it an `onDismiss` callback, and it runs that callback either on unmount, or when the `AppState` changes to `"background"`. Under the hood, the hook uses `useEffectEvent`, so there is no …

True Dismissal

---

.eslintrc.json
lib/SQLite.ts
lib/Sqlite.test.ts
test-helpers/SQLite.ts

The purpose of this PR is to separate the logs from the main tables of the SQLite database, where settings, location placemarks, etc. are stored. This is done in order to easily create a copy of them for importing purposes, or to access the current ones in a more isolated database. 
1. In order to adjust the implementation of the database, we needed to adjust the TiFSQLite class.
2. Going there, we remove its `migrateV1` function in favour of a more generic `migrate` parameter, so that we can specify what gets run for the database.
3. We add a namespace with two functions: `main`, which makes most tables, and `logs`, which makes only the logs table. 
4. We adjust any implementations of `TiFSQLite` or `testSQLite` accordingly.

Logs + Main SQLite DB separation

---

.github/workflows/pull_request_template.md

PR quality should be improved.
Add a PR template to encourage explaining the purpose and details of the PR. This should ensure every PR is meaningful.
* Added pull_request_template.md file to .github folder
Opening a PR should pre-populate the form with the template.
Needs to be merged in to test.
TASK_pyLuAoOS

Add pull request template

---

.watchmanconfig

Ignoring "node_modules" should reduce the amount of files being tracked when expo starts up
https://facebook.github.io/watchman/docs/config
TASK_UNTRACKED

Add watchmanconfig to try and improve expo startup time

---

lib/Platform.ts
settings-boundary/AppearanceSettings.tsx

iOS 18 did something to shift the rendering of the open dyslexic font option preview downwards so that it wasn't aligned with the open sans option. Therefore, I applied the same offset to the preview view as I did to the label, but only on iOS 18 and above. I also added a couple of helpers in determining and comparing the OS major version.
TASK_UNTRACKED

Settings: Open Dyslexic iOS 18 Alignment Fix

---

lib/EmailComposition.ts
package-lock.json
package.json

The help and support screen (and possibly future screens) present a success alert when the user sends an email successfully through the mail composer. Unfortunately, Android does not give access to this information, but expo still decides it's a good idea to return `MailComposerStatus.SENT` even if the user did not send an email. Due to this, it's possible for a "We received your feedback!" alert to be presented even when no email was sent on Android.
There are 2 possible fixes for this:
1. Check that both the status is `MailComposerStatus.SENT` and that `Platform.OS === "android"` every time we need to evaluate the result of a mail composition session.
2. Wrap `expo-mail-composer`'s `composeAsync` function and return a custom `EmailCompositionResult` union type based on the check from …

Mail Composer Wrapper

---

.storybook/components/SettingsScreen/SettingsScreen.stories.tsx
lib/EmailComposition.ts
settings-boundary/HelpAndSupport.test.tsx
settings-boundary/HelpAndSupport.tsx

Updates the emails in the help and support settings screen with formal language. For the emails, I added a little bit of HTML to make all the sections bolded.
I also did some minor cleanup on the hook code.
https://trello.com/c/uouGSTlN

Settings: Help and Support Email Templates Language

---

roswaal/Client.test.ts
roswaal/TestCase.test.ts
roswaal/TestCase.ts

Updates the shape of the upload request to match the latest fields from the roswaal tool. The biggest change is how we're now using a failure index (`commandFailureOrdinal`) instead of having a `didPass` field for every step.
https://trello.com/c/UH6YeaPS

Roswaal: Upload Format Update

---

.github/workflows/auto-pass.yml
.github/workflows/build.yml

For roswaal PR's or any other PR that is unimportant, we want the option to skip the long build steps.
TASK_UNTRACKED

IGNORE_BUILD: Conditionally pass build step

---

edit-event/PragmaQuotes.test.ts
edit-event/PragmaQuotes.ts

We've talked about adding a bit of personality on the edit event screen in the form of Pragma (accompanying character) asking a question (eg. "What event do you want to create?") instead of saying a generic "Create Event".
This PR implements a random generation of quotes that they can say depending on whether you're creating a new event or editing an existing event.
For editing, I decided to keep it simple and only return a random quote in a list of 3 quotes. When a user is editing an event, it usually occurs due to some change in external circumstances, and their not likely to care much that Christmas is coming up, so I don't think they need to be too encouraging.
There are 4 kinds of quotes that Pragma can say when creating an event.
1. Start of the week motivation.
2. Weekend …

Edit Event: Pragma Quotes

---

arrival-tracking/Tracker.test.ts
arrival-tracking/Tracker.ts
arrival-tracking/region-monitoring/EventArrivalsTrackerRegionMonitor.test.ts

Makes `EventArrivalsTracker.startTracking` unconditionally subscribe to the geofencer no matter how many arrivals are stored. This allows `startTracking` to be made into a synchronous function, which is necessary because we need to call it before calling `ExpoEventArrivalsGeofencer.shared.defineTask()` to not miss geofencing updates in the background.

Event Arrivals: Unconditionally Subscribe to Geofencer

---

arrival-tracking/Storage.test.ts
arrival-tracking/Storage.ts
arrival-tracking/Tracker.test.ts
arrival-tracking/Tracker.ts
arrival-tracking/region-monitoring/EventArrivalsTrackerRegionMonitor.test.ts

There was a complex infinite loop that occurred with the `EventArrivalsTracker` which would cause the background task to run repeatedly, and spam requests to the backend. For brevity, here is the description of the loop from slack.
The fix is to deduplicate arrival operations when the updated `hasArrived` matches the stored `hasArrived`. I added a new method requirement to the `EventArrivalsStorage` to return the `hasArrived` value for a particular stored region, and then called this inside `handleGeofencingEvent` in `EventArrivalsTracker`.
https://trello.com/c/28WJIizX

Event Arrivals: Deduplicate Arrival Operations

---

arrival-tracking/region-monitoring/EventArrivalsTrackerRegionMonitor.test.ts
arrival-tracking/region-monitoring/ForegroundRegionMonitor.test.ts
arrival-tracking/region-monitoring/ForegroundRegionMonitor.ts
arrival-tracking/region-monitoring/TestHelpers.ts

When dealing with foreground location updates in `ForegroundEventRegionMonitor`, we buffered any location update by 20 seconds. The original intent of this behavior was to prevent the UI from being spammed with many updates if the user was constantly walking in and out of the arrival radius.
Based on our field tests, this behavior caused many inaccuracies compared to the results of `EventArrivalsTrackerRegionMonitor`. At first, I wanted just to reduce the delay, however, I think it's best that we remove it entirely for the following reasons:
1. Foreground location updates don't happen as often as we think. Even with the highest accuracy, you have to walk quite far (usually ~1 minute in any direction) before a new location is delivered to the app.
2. Even if the above weren't true, there …

Arrivals: Remove Buffer Time from `ForegroundEventRegionMonitor`

---

.storybook/components/Buttons/Buttons.stories.tsx
.storybook/components/SettingsScreen/EventSettingsDurations.stories.tsx
auth-boundary/AuthLayout.tsx
components/Buttons.tsx
content-reporting-boundary/Success.tsx
explore-events-boundary/ExploreEvents.tsx

Increases the height of `PrimaryButton` so that it stands out more as a CTA. Additionally, I also removed the legacy `title` prop as nothing was using it anymore.

Better Primary Button

---

.storybook/components/EditEvent/PragmaQuote.stories.tsx
auth-boundary/AuthLayout.tsx
components/Footer.tsx
components/form-components/ScrollView.tsx
components/form-components/ScrollableFormLayout.tsx
edit-event-boundary/EditEvent.tsx

Adds 2 new views:
1. `TiFFooterView` which is a footer that we can use for forms and the tab bar for the updated explore screen design.
2. `TiFFormScrollableLayoutView` which can be used to easily create scrollable screens that render a footer at the bottom.
Here's a simple look at the new footer on the edit event form. The background color is now the card color to help make the CTA standout a bit more.

Common Footer View

---

event-details-boundary/Details.tsx
lib/utils/Form.ts
user/FriendRequest.test.tsx
user/FriendRequest.tsx

We'll have multiple UI elements in the app that have the ability to both send and accept friend requests. However, the logic and friend request specific UI for these UI elements will be the same, so I decided to extract that logic and shared friend request UI into a `FriendRequestView` and `useFriendRequest` hook respectively.
https://trello.com/c/hESd3xVW

Friend Request: Generic Friend Request View

---

.storybook/.ondevice/storybook.requires.ts
.storybook/App.tsx
.storybook/components/EventDetails/EventDetails.stories.tsx
.storybook/components/SignIn/SignIn.stories.tsx
.storybook/components/SignUp/SignUp.stories.tsx
App.tsx
api/TiFAPI.test.ts
api/TiFAPI.ts
api/index.ts
babel.config.js
components/Avatar.tsx
components/CalendarDay.tsx
components/profileImageComponents/ProfileCircle.tsx
components/profileImageComponents/ProfileImageAndName.tsx
core-root/NameEntry.tsx
event/EventCard.test.tsx
event/EventCard.tsx
event/JoinEvent.tsx
event/LeaveEvent.tsx
event/Menu.test.tsx
event/Menu.tsx
event/UserAttendance.tsx
tsconfig.json
user/Blocking.tsx
user/alpha/AlphaUser.test.ts
user/alpha/AlphaUser.tsx
user/alpha/MockData.ts
user/alpha/index.ts
user/privacy/EmailAddress.ts

Implements the data layer for storing alpha users. I didn't nuke the production user system that we plan on using, but rather integrated the alpha auth system alongside it. For all intensive purposes, the alpha auth system may be a decent way to implement an anonymous account feature down the line.
I introduced an `AlphaUserStorage` class that stores the access token for the alpha user. Since that token never expires, and since it holds all the user data in its body, we can retrieve the user details by decoding the body of the JWT instead of having to hit the API. You can use `AlphaUserStorage` with the `AlphaUserSessionProvider` component to integrate the alpha user data with `useUserSessionQuery` or `useIsSignedIn`.
Lastly, I had to move the `TiFAPI` production instance into a dedicated …

Alpha User Storage
